server:
  port: 8081

spring:
  application:
    name: PRODUCT-SERVICE
  config:
    import: optional:configserver:http://${CONFIG_SERVER_URL:localhost}:9296
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/product-dev
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    show-sql: 'true'

#  redis:
#    host: localhost
#    port: 6379
#  cache:
#    redis:
#      time-to-live: 600000
#      key-prefix: jdj
#    cache-names: product

#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}

#message:
#  config: is inside of ProductController

