server:
  port: 8085
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    password: root
    username: root
    url: jdbc:mysql://localhost:3306/user-dev
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
    show-sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ankaalish@gmail.com
    password: kvnzqzrclcyyduab

    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000