server:
  port: 8082

spring:
  application:
    name: ORDER-SERVICE
  config:
    import: optional:configserver:http://${CONFIG_SERVER_URL:localhost}:9296
#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          issuer-uri: https://dev-05976822.okta.com/oauth2/default
#      client:
#        registration:
#          internal-client:
#            provider: okta
#            authorization-grant-type: client_credentials
#            scope: internal
#            client-id: 0oa7s0igtej0Jma9c5d7
#            client-secret: k6V8n9FWWgpwPP3AitUivYCP6GvRQvkfvsqQdO1x
#        provider:
#          okta:
#            issuer-uri: https://dev-05976822.okta.com/oauth2/default
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/order-dev
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    show-sql: 'true'

#resilience4j:
#  circuitbreaker:
#    instances:
#      external:
#        event-consumer-buffer-size: 10
#        failure-rate-threshold: 50
#        minimum-number-of-calls: 5
#        automatic-transition-from-open-to-half-open-enabled: true
#        wait-duration-in-open-state: 5s
#        permitted-number-of-calls-in-half-open-state: 3
#        sliding-window-size: 10
#        sliding-window-type: COUNT_BASED


#  profiles: dev
#  redis:
#    host: localhost
#    port: 6379
#  cache:
#    redis:
#      time-to-live: 600000
#      key-prefix: jdj
#    cache-names: product
#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}

#message:
#  config: is inside of ProductController

#---
#spring:
#  profiles: prod